services:
  - type: web
    name: wish-orbit
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: wish-orbit-db
          property: connectionString

databases:
  - name: wish-orbit-db
    plan: free
